[cygwin] fixed not working charset conversion, now use win32 native function.

diff --git a/julius/configure b/julius/configure
--- a/julius/configure
+++ b/julius/configure
@@ -1506,28 +1506,47 @@ fi
 if test "$use_charconv" = no; then
     CCOBJ=""
 else
-    echo $ac_n "checking for charset conversion""... $ac_c" 1>&6
-echo "configure:1511: checking for charset conversion" >&5
-    CCOBJ="charconv.o"
-    case "$host_os" in
-    mingw*)
-		cat >> confdefs.h <<\EOF
-#define USE_WIN32_MULTIBYTE 1
-EOF
-
-        CCOBJ="${CCOBJ} charconv_win32.o"
-	CCOBJ="${CCOBJ} charconv_libjcode.o libjcode/libjcode.o libjcode/detect.o"
-	ccdesc="Win32 API + libjcode"
-	cat >> confdefs.h <<\EOF
-#define CHARACTER_CONVERSION 1
-EOF
-
-	echo "$ac_t""win32" 1>&6
-	;;
-*)
-	case "$use_charconv" in
+        CCOBJ="charconv.o"
+    case "$use_charconv" in
 	auto)
-                        
+	    	    ac_safe=`echo "winnls.h" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for winnls.h""... $ac_c" 1>&6
+echo "configure:1515: checking for winnls.h" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1520 "configure"
+#include "confdefs.h"
+#include <winnls.h>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1525: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  use_winnls=yes
+else
+  echo "$ac_t""no" 1>&6
+use_winnls=no
+fi
+
+	    if test "$use_winnls" = yes; then
+	       use_cfunc=win32
+	    else
+	       	       
     
   # Check whether --with-libiconv-prefix or --without-libiconv-prefix was given.
 if test "${with_libiconv_prefix+set}" = set; then
@@ -1542,7 +1561,7 @@ fi
 
 
   echo $ac_n "checking for iconv""... $ac_c" 1>&6
-echo "configure:1546: checking for iconv" >&5
+echo "configure:1565: checking for iconv" >&5
 if eval "test \"`echo '$''{'am_cv_func_iconv'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1550,7 +1569,7 @@ else
     am_cv_func_iconv="no, consider installing GNU libiconv"
     am_cv_lib_iconv=no
     cat > conftest.$ac_ext <<EOF
-#line 1554 "configure"
+#line 1573 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <iconv.h>
@@ -1560,7 +1579,7 @@ iconv_t cd = iconv_open("","");
        iconv_close(cd);
 ; return 0; }
 EOF
-if { (eval echo configure:1564: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1583: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   am_cv_func_iconv=yes
 else
@@ -1572,7 +1591,7 @@ rm -f conftest*
       am_save_LIBS="$LIBS"
       LIBS="$LIBS -liconv"
       cat > conftest.$ac_ext <<EOF
-#line 1576 "configure"
+#line 1595 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <iconv.h>
@@ -1582,7 +1601,7 @@ iconv_t cd = iconv_open("","");
          iconv_close(cd);
 ; return 0; }
 EOF
-if { (eval echo configure:1586: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1605: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   am_cv_lib_iconv=yes
         am_cv_func_iconv=yes
@@ -1603,13 +1622,13 @@ echo "$ac_t""$am_cv_func_iconv" 1>&6
 EOF
 
     echo $ac_n "checking for iconv declaration""... $ac_c" 1>&6
-echo "configure:1607: checking for iconv declaration" >&5
+echo "configure:1626: checking for iconv declaration" >&5
     if eval "test \"`echo '$''{'am_cv_proto_iconv'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   
       cat > conftest.$ac_ext <<EOF
-#line 1613 "configure"
+#line 1632 "configure"
 #include "confdefs.h"
 
 #include <stdlib.h>
@@ -1628,7 +1647,7 @@ int main() {
 
 ; return 0; }
 EOF
-if { (eval echo configure:1632: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1651: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   am_cv_proto_iconv_arg1=""
 else
@@ -1655,189 +1674,242 @@ EOF
   fi
   
 
-            if test "$am_cv_func_iconv" = yes; then
-	       CCOBJ="${CCOBJ} charconv_iconv.o"
-               ccdesc="iconv library"
-	       echo "$ac_t""iconv" 1>&6
-            else
-               cat >> confdefs.h <<\EOF
-#define USE_LIBJCODE 1
+	       if test "$am_cv_func_iconv" = yes; then
+	          use_cfunc=iconv
+	       else
+	          use_cfunc=libjcode
+	       fi
+	    fi
+	    ;;
+	win)
+	    	    ac_safe=`echo "winnls.h" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for winnls.h""... $ac_c" 1>&6
+echo "configure:1688: checking for winnls.h" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1693 "configure"
+#include "confdefs.h"
+#include <winnls.h>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1698: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  use_winnls=yes
+else
+  echo "$ac_t""no" 1>&6
+use_winnls=no
+fi
+
+	    if test "$use_winnls" = yes; then
+	       use_cfunc=win32
+	    else
+	       use_cfunc=no
+               { echo "configure: error: Win32 function not found!" 1>&2; exit 1; }
+	    fi
+	    ;;
+	iconv)
+	    	    
+    
+  # Check whether --with-libiconv-prefix or --without-libiconv-prefix was given.
+if test "${with_libiconv_prefix+set}" = set; then
+  withval="$with_libiconv_prefix"
+  
+    for dir in `echo "$withval" | tr : ' '`; do
+      if test -d $dir/include; then CPPFLAGS="$CPPFLAGS -I$dir/include"; fi
+      if test -d $dir/lib; then LDFLAGS="$LDFLAGS -L$dir/lib"; fi
+    done
+   
+fi
+
+
+  echo $ac_n "checking for iconv""... $ac_c" 1>&6
+echo "configure:1743: checking for iconv" >&5
+if eval "test \"`echo '$''{'am_cv_func_iconv'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+    am_cv_func_iconv="no, consider installing GNU libiconv"
+    am_cv_lib_iconv=no
+    cat > conftest.$ac_ext <<EOF
+#line 1751 "configure"
+#include "confdefs.h"
+#include <stdlib.h>
+#include <iconv.h>
+int main() {
+iconv_t cd = iconv_open("","");
+       iconv(cd,NULL,NULL,NULL,NULL);
+       iconv_close(cd);
+; return 0; }
+EOF
+if { (eval echo configure:1761: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  am_cv_func_iconv=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+rm -f conftest*
+    if test "$am_cv_func_iconv" != yes; then
+      am_save_LIBS="$LIBS"
+      LIBS="$LIBS -liconv"
+      cat > conftest.$ac_ext <<EOF
+#line 1773 "configure"
+#include "confdefs.h"
+#include <stdlib.h>
+#include <iconv.h>
+int main() {
+iconv_t cd = iconv_open("","");
+         iconv(cd,NULL,NULL,NULL,NULL);
+         iconv_close(cd);
+; return 0; }
+EOF
+if { (eval echo configure:1783: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  am_cv_lib_iconv=yes
+        am_cv_func_iconv=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+rm -f conftest*
+      LIBS="$am_save_LIBS"
+    fi
+  
+fi
+
+echo "$ac_t""$am_cv_func_iconv" 1>&6
+  if test "$am_cv_func_iconv" = yes; then
+    cat >> confdefs.h <<\EOF
+#define HAVE_ICONV 1
 EOF
 
-	       CCOBJ="${CCOBJ} charconv_libjcode.o libjcode/libjcode.o libjcode/detect.o"
-               ccdesc="built-in libjcode (Japanese codes only)"
-	       echo "$ac_t""libjcode" 1>&6
-            fi
+    echo $ac_n "checking for iconv declaration""... $ac_c" 1>&6
+echo "configure:1804: checking for iconv declaration" >&5
+    if eval "test \"`echo '$''{'am_cv_proto_iconv'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+      cat > conftest.$ac_ext <<EOF
+#line 1810 "configure"
+#include "confdefs.h"
+
+#include <stdlib.h>
+#include <iconv.h>
+extern
+#ifdef __cplusplus
+"C"
+#endif
+#if defined(__STDC__) || defined(__cplusplus)
+size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
+#else
+size_t iconv();
+#endif
+
+int main() {
+
+; return 0; }
+EOF
+if { (eval echo configure:1829: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+  rm -rf conftest*
+  am_cv_proto_iconv_arg1=""
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  am_cv_proto_iconv_arg1="const"
+fi
+rm -f conftest*
+      am_cv_proto_iconv="extern size_t iconv (iconv_t cd, $am_cv_proto_iconv_arg1 char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);"
+fi
+
+    am_cv_proto_iconv=`echo "$am_cv_proto_iconv" | tr -s ' ' | sed -e 's/( /(/'`
+    echo "$ac_t""${ac_t:-
+         }$am_cv_proto_iconv" 1>&6
+    cat >> confdefs.h <<EOF
+#define ICONV_CONST $am_cv_proto_iconv_arg1
+EOF
+
+  fi
+  LIBICONV=
+  if test "$am_cv_lib_iconv" = yes; then
+    LIBICONV="-liconv"
+  fi
+  
+
+	    if test "$am_cv_func_iconv" = yes; then
+	       use_cfunc=iconv
+	    else
+	       use_cfunc=no
+               { echo "configure: error: iconv function not found!" 1>&2; exit 1; }
+	    fi
+	    ;;
+	no)
+	    use_cfunc=no
+	    ;;
+	*)
+                        { echo "configure: error: wrong argument for --enable-charconv" 1>&2; exit 1; }
+	    ;;
+    esac
+    echo $ac_n "checking for charset conversion""... $ac_c" 1>&6
+echo "configure:1871: checking for charset conversion" >&5
+    case "$use_cfunc" in
+	win32)
+	    cat >> confdefs.h <<\EOF
+#define CHARACTER_CONVERSION 1
+EOF
+
+	    cat >> confdefs.h <<\EOF
+#define USE_WIN32_MULTIBYTE 1
+EOF
+
+	    CCOBJ="${CCOBJ} charconv_win32.o"
+	    CCOBJ="${CCOBJ} charconv_libjcode.o libjcode/libjcode.o libjcode/detect.o"
+	    ccdesc="Win32 API + libjcode"
+	    echo "$ac_t""win32" 1>&6
+	    ;;
+	iconv)
             cat >> confdefs.h <<\EOF
 #define CHARACTER_CONVERSION 1
 EOF
 
-            ;;
-        iconv)
-                        
-    
-  # Check whether --with-libiconv-prefix or --without-libiconv-prefix was given.
-if test "${with_libiconv_prefix+set}" = set; then
-  withval="$with_libiconv_prefix"
-  
-    for dir in `echo "$withval" | tr : ' '`; do
-      if test -d $dir/include; then CPPFLAGS="$CPPFLAGS -I$dir/include"; fi
-      if test -d $dir/lib; then LDFLAGS="$LDFLAGS -L$dir/lib"; fi
-    done
-   
-fi
-
-
-  echo $ac_n "checking for iconv""... $ac_c" 1>&6
-echo "configure:1693: checking for iconv" >&5
-if eval "test \"`echo '$''{'am_cv_func_iconv'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  
-    am_cv_func_iconv="no, consider installing GNU libiconv"
-    am_cv_lib_iconv=no
-    cat > conftest.$ac_ext <<EOF
-#line 1701 "configure"
-#include "confdefs.h"
-#include <stdlib.h>
-#include <iconv.h>
-int main() {
-iconv_t cd = iconv_open("","");
-       iconv(cd,NULL,NULL,NULL,NULL);
-       iconv_close(cd);
-; return 0; }
-EOF
-if { (eval echo configure:1711: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  am_cv_func_iconv=yes
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-fi
-rm -f conftest*
-    if test "$am_cv_func_iconv" != yes; then
-      am_save_LIBS="$LIBS"
-      LIBS="$LIBS -liconv"
-      cat > conftest.$ac_ext <<EOF
-#line 1723 "configure"
-#include "confdefs.h"
-#include <stdlib.h>
-#include <iconv.h>
-int main() {
-iconv_t cd = iconv_open("","");
-         iconv(cd,NULL,NULL,NULL,NULL);
-         iconv_close(cd);
-; return 0; }
-EOF
-if { (eval echo configure:1733: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  am_cv_lib_iconv=yes
-        am_cv_func_iconv=yes
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-fi
-rm -f conftest*
-      LIBS="$am_save_LIBS"
-    fi
-  
-fi
-
-echo "$ac_t""$am_cv_func_iconv" 1>&6
-  if test "$am_cv_func_iconv" = yes; then
-    cat >> confdefs.h <<\EOF
-#define HAVE_ICONV 1
-EOF
-
-    echo $ac_n "checking for iconv declaration""... $ac_c" 1>&6
-echo "configure:1754: checking for iconv declaration" >&5
-    if eval "test \"`echo '$''{'am_cv_proto_iconv'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  
-      cat > conftest.$ac_ext <<EOF
-#line 1760 "configure"
-#include "confdefs.h"
-
-#include <stdlib.h>
-#include <iconv.h>
-extern
-#ifdef __cplusplus
-"C"
-#endif
-#if defined(__STDC__) || defined(__cplusplus)
-size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
-#else
-size_t iconv();
-#endif
-
-int main() {
-
-; return 0; }
-EOF
-if { (eval echo configure:1779: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
-  rm -rf conftest*
-  am_cv_proto_iconv_arg1=""
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  am_cv_proto_iconv_arg1="const"
-fi
-rm -f conftest*
-      am_cv_proto_iconv="extern size_t iconv (iconv_t cd, $am_cv_proto_iconv_arg1 char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);"
-fi
-
-    am_cv_proto_iconv=`echo "$am_cv_proto_iconv" | tr -s ' ' | sed -e 's/( /(/'`
-    echo "$ac_t""${ac_t:-
-         }$am_cv_proto_iconv" 1>&6
-    cat >> confdefs.h <<EOF
-#define ICONV_CONST $am_cv_proto_iconv_arg1
-EOF
-
-  fi
-  LIBICONV=
-  if test "$am_cv_lib_iconv" = yes; then
-    LIBICONV="-liconv"
-  fi
-  
-
-            if test "$am_cv_func_iconv" = yes; then
-	       CCOBJ="${CCOBJ} charconv_iconv.o"
-               EXTRALIB="$EXTRALIB $LIBICONV"
-               cat >> confdefs.h <<\EOF
+	    CCOBJ="${CCOBJ} charconv_iconv.o"
+            ccdesc="iconv library"
+	    echo "$ac_t""iconv" 1>&6
+	    ;;
+	libjcode)
+            cat >> confdefs.h <<\EOF
 #define CHARACTER_CONVERSION 1
 EOF
 
-               ccdesc="iconv libraru"
-	       echo "$ac_t""iconv" 1>&6
-            else
-	       CCOBJ=""
-               ccdesc="no"
-               { echo "configure: error: iconv function not found!" 1>&2; exit 1; }
-	       echo "$ac_t""no" 1>&6
-            fi
-            ;;
-        libjcode)
-                        cat >> confdefs.h <<\EOF
+            cat >> confdefs.h <<\EOF
 #define USE_LIBJCODE 1
 EOF
 
 	    CCOBJ="${CCOBJ} charconv_libjcode.o libjcode/libjcode.o libjcode/detect.o"
             ccdesc="built-in libjcode (Japanese codes only)"
-            cat >> confdefs.h <<\EOF
-#define CHARACTER_CONVERSION 1
-EOF
-
 	    echo "$ac_t""libjcode" 1>&6
-            ;;
-        no)
-                        ccdesc="no"
+	    ;;
+	no)
+	    CCOBJ=""
+            ccdesc="no"
 	    echo "$ac_t""no" 1>&6
             ;;
-        *)
-                        { echo "configure: error: wrong argument for charconv!" 1>&2; exit 1; }
-        esac
     esac
 fi
 
